name: Update Calendar Events

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run update-calendar script
        run: node scripts/update-calendar.js
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code --quiet src/data/calendar-events.json || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add src/data/calendar-events.json
          
          # Run CI if there are changes, skip CI if no new events
          if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
            git commit -m "Update calendar events with new data" && git push
          else
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar events [skip ci]" && git push)
          fi