name: Validate JSON

on:
  push:
    paths:
      - 'src/data/**/*.json'
  pull_request:
    paths:
      - 'src/data/**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install ajv-cli
      run: npm install -g ajv-cli ajv-formats

    - name: Validate conferences.json
      run: |
        ajv validate -s src/data/schemas/conferences.schema.json -d src/data/conferences.json --strict=false --all-errors

    - name: Validate meetups-combined.json
      run: |
        ajv validate -s src/data/schemas/meetups.schema.json -d src/data/meetups-combined.json --strict=false --all-errors
